import pytest

from autoflow.auth import password_hash, password_matches, set_session_cookie


def test_password_hash_roundtrip():
    encoded = password_hash("development-password")
    assert ":" in encoded
    assert password_matches("development-password", encoded)
    assert not password_matches("wrong-password", encoded)


def test_password_hash_matches_node_fixture():
    # Generated by Node's crypto.scryptSync with N=16384, r=8, p=1, dklen=64.
    fixture = (
        "c2FsdDEyMzQ1Njc4OTAxMg"
        ":28BOCzhEoP_N8tysAhseFwfWk_qaLX-8nBdud_AMI2QeO9qJdlvPaJG2ssx54WIq1VKIkwRa_9yeQLDBAKbU3Q"
    )
    assert password_matches("development-password", fixture)
    assert not password_matches("development-password!", fixture)


def test_password_matches_rejects_bad_encoding():
    assert not password_matches("development-password", "not-a-hash")


def test_session_cookie_is_secure_by_default(monkeypatch):
    monkeypatch.delenv("AUTOFLOW_COOKIE_SECURE", raising=False)
    cookie = set_session_cookie("token", "2026-08-21T10:00:00Z")
    assert "; Secure" in cookie


def test_session_cookie_secure_can_be_opt_out(monkeypatch):
    monkeypatch.setenv("AUTOFLOW_COOKIE_SECURE", "0")
    cookie = set_session_cookie("token", "2026-08-21T10:00:00Z")
    assert "; Secure" not in cookie
